# Generated by Django 5.2 on 2025-04-25 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_irr', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='exchange.warehouse')),
            ],
        ),
    ]
